"""Real browser voice failures preserve editable text and durable turn identity.

Microphone audio is generated by the shared helper, not a physical device.
"""

from pathlib import Path

import httpx
import pytest
from _voice_microphone import install_microphone
from playwright.async_api import Locator, Page, Route, async_playwright, expect
from test_sim_authenticated import login
from test_sim_roundtrip import servers  # noqa: F401

pytestmark = [
    pytest.mark.browser,
    pytest.mark.parametrize(
        "servers", [{"app": "voice_session_app", "auth": True, "practice": True}], indirect=True
    ),
]


async def _open_session(page: Page, api: str, web: str) -> tuple[str, str, Locator]:
    async with page.expect_response(
        lambda response: (
            response.url.endswith("/api/live/sessions") and response.request.method == "POST"
        )
    ) as opened:
        await page.goto(f"{web}/tests/voice-session.html?api={api}")
    session = await (await opened.value).json()
    token = await page.evaluate(
        "JSON.parse(localStorage.getItem('sb-identity-auth-token')).access_token"
    )
    voice = page.get_by_role("region", name="Voice controls")
    await expect(voice.get_by_role("button", name="Speak", exact=True)).to_be_enabled()
    return session["sessionId"], token, voice


async def test_mobile_permission_denial_keeps_keyboard_answer(
    servers: tuple[str, str],  # noqa: F811
    tmp_path: Path,
) -> None:
    api, web = servers
    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch()
        page = await login(browser)
        await page.set_viewport_size({"width": 390, "height": 844})
        await page.add_init_script("""navigator.mediaDevices.getUserMedia = async () => {
          throw new DOMException('Permission denied', 'NotAllowedError');
        };""")
        sid, token, voice = await _open_session(page, api, web)
        async with httpx.AsyncClient(
            base_url=api, headers={"Authorization": f"Bearer {token}"}
        ) as client:
            before = (await client.get(f"/api/live/sessions/{sid}")).json()
            speak = voice.get_by_role("button", name="Speak", exact=True)
            await speak.focus()
            await speak.press("Enter")
            await expect(voice.get_by_role("alert")).to_contain_text("Microphone access")
            await expect(page.get_by_role("textbox", name="Your answer")).to_have_count(1)
            assert (await client.get(f"/api/live/sessions/{sid}")).json() == before
            assert (await client.get("/test/voice-calls")).json()["transcriptions"] == []
            answer = page.get_by_role("textbox", name="Your answer")
            await answer.focus()
            await answer.press_sequentially("Doubling x doubles y because y equals twice x.")
            await page.screenshot(
                path=str(tmp_path / "voice-mobile-permission-denied.png"), full_page=True
            )
            assert await page.evaluate("document.documentElement.scrollWidth <= window.innerWidth")
            async with page.expect_response(
                lambda response: response.url.endswith("/turns")
            ) as sent:
                await answer.press("Control+Enter")
            assert (await sent.value).status == 200
            after = (await client.get(f"/api/live/sessions/{sid}")).json()
            assert len(after["turns"]) == len(before["turns"]) + 1
            assert after["turns"][0]["answer"] == "Doubling x doubles y because y equals twice x."
        await browser.close()


async def test_lost_transcription_response_replays_without_duplicate_charge(
    servers: tuple[str, str],  # noqa: F811
    tmp_path: Path,
) -> None:
    api, web = servers
    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch()
        page = await login(browser)
        await install_microphone(page)
        sid, token, voice = await _open_session(page, api, web)
        operations: list[str] = []

        async def lose_first_response(route: Route) -> None:
            operations.append(route.request.headers["idempotency-key"])
            response = await route.fetch()
            assert response.status == 200
            if len(operations) == 1:
                await route.abort("failed")
            else:
                await route.fulfill(response=response)

        await page.route("**/voice/transcriptions?*", lose_first_response)
        async with httpx.AsyncClient(
            base_url=api, headers={"Authorization": f"Bearer {token}"}
        ) as client:
            before = (await client.get(f"/api/live/sessions/{sid}")).json()
            await voice.get_by_role("button", name="Speak", exact=True).click()
            await expect(voice.get_by_role("button", name="Finish recording")).to_be_visible()
            await page.wait_for_function("window.micContexts.at(-1).currentTime >= 0.25")
            await voice.get_by_role("button", name="Finish recording").click()
            await expect(voice.get_by_role("alert")).to_contain_text("Transcription is unavailable")
            assert (await client.get(f"/api/live/sessions/{sid}")).json() == before
            await voice.get_by_role("button", name="Retry transcription").click()
            answer = page.get_by_role("textbox", name="Your answer")
            await expect(answer).to_have_value("A fraction is a part of a whole.")
            assert len(operations) == 2 and operations[0] == operations[1]
            assert len((await client.get("/test/voice-calls")).json()["transcriptions"]) == 1
            assert (await client.get(f"/api/live/sessions/{sid}")).json() == before
            assert await page.evaluate(
                "window.micStreams.every(s => s.getTracks().every(t => t.readyState === 'ended'))"
            )
            await page.screenshot(
                path=str(tmp_path / "voice-retry-reviewed-draft.png"), full_page=True
            )
            async with page.expect_response(
                lambda response: response.url.endswith("/turns")
            ) as sent:
                await answer.press("Control+Enter")
            assert (await sent.value).status == 200
            after = (await client.get(f"/api/live/sessions/{sid}")).json()
            assert len(after["turns"]) == len(before["turns"]) + 1
            assert after["turns"][0]["answer"] == "A fraction is a part of a whole."
        await browser.close()


async def test_cancel_recording_stop_audio_and_reload_preserve_turn(
    servers: tuple[str, str],  # noqa: F811
) -> None:
    api, web = servers
    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch()
        page = await login(browser)
        await install_microphone(page)
        sid, token, voice = await _open_session(page, api, web)
        async with httpx.AsyncClient(
            base_url=api, headers={"Authorization": f"Bearer {token}"}
        ) as client:
            before = (await client.get(f"/api/live/sessions/{sid}")).json()
            await voice.get_by_role("button", name="Speak", exact=True).click()
            await expect(voice.get_by_role("button", name="Finish recording")).to_be_visible()
            await voice.get_by_role("button", name="Cancel recording").click()
            assert await page.evaluate(
                "window.micStreams.length === 1 && "
                "window.micStreams.every(s => s.getTracks().every(t => t.readyState === 'ended'))"
            )
            assert (await client.get("/test/voice-calls")).json()["transcriptions"] == []

            async def extend_fixture_audio(route: Route) -> None:
                response = await route.fetch()
                # Stretch fixture PCM at the network boundary so Stop is deterministic.
                await route.fulfill(response=response, body=(await response.body()) * 20)

            await page.route("**/voice/speech", extend_fixture_audio)
            await voice.get_by_role("button", name="Read aloud", exact=True).click()
            await expect(voice.get_by_role("status")).to_have_text("Playing audio")
            await voice.get_by_role("button", name="Stop audio").click()
            await expect(voice.get_by_role("button", name="Read aloud", exact=True)).to_be_enabled()
            assert (await client.get(f"/api/live/sessions/{sid}")).json() == before
            calls_before_reload = (await client.get("/test/voice-calls")).json()
            async with page.expect_response(
                lambda response: (
                    response.url.endswith("/api/live/sessions")
                    and response.request.method == "POST"
                )
            ) as resumed:
                await page.reload()
            # SessionView starts a new text session on remount; voice must not
            # mutate or rebill the original session during that navigation.
            assert (await (await resumed.value).json())["sessionId"] != sid
            await expect(page.get_by_role("button", name="Speak", exact=True)).to_be_enabled()
            assert await page.evaluate("window.micStreams.length") == 0
            assert (await client.get("/test/voice-calls")).json() == calls_before_reload
            assert (await client.get(f"/api/live/sessions/{sid}")).json() == before
        await browser.close()
