from typing import Protocol

from ..models.claim import GraphClaim
from ..models.mutation import SessionMutation


class IGraphTransactionBackend(Protocol):
    def acquire(self, graph_id: str, *, owner_id: str | None) -> GraphClaim | None: ...
    def renew(self, claim: GraphClaim) -> bool: ...
    def paid(self, claim: GraphClaim, operation_key: str) -> bool: ...
    def commit(self, claim: GraphClaim, mutation: SessionMutation) -> None: ...
    def release(self, claim: GraphClaim) -> None: ...
