from dataclasses import replace

import pytest
from lunaris_live.sims.schema.event import SimEvent
from lunaris_live.sims.schema.exchange import SimExchange
from lunaris_live.sims.schema.reaction import SimReaction
from lunaris_live.voice.durable_service import DurableVoiceService
from lunaris_live.voice.error import VoiceError
from lunaris_live.voice.models.dependencies import VoiceDependencies
from lunaris_live.voice.persistence.memory_audio_store import MemoryVoiceAudioStore
from test_voice_durable_service import Sessions, operation, system


def exchange(sequence: int) -> SimExchange:
    return SimExchange(
        event=SimEvent(
            version=1,
            instance_id="r",
            turn_seq=1,
            sequence=sequence,
            app_id="fixture",
            kind="param_changed",
            state={"x": float(sequence)},
        ),
        reaction=SimReaction(text=f"Reaction {sequence}", state={"x": float(sequence)}),
        run_id=f"reaction-{sequence}",
    )


class ObservedAudio(MemoryVoiceAudioStore):
    stored_key: str | None = None

    async def put(self, key: str, pcm: bytes) -> None:
        self.stored_key = key
        await super().put(key, pcm)


@pytest.mark.asyncio
@pytest.mark.parametrize("change", ["turn", "reaction"])
async def test_streaming_source_change_refuses_cache_and_restart_replay(change: str) -> None:
    # Arrange: speech is already producing bytes for an authoritative source.
    _, provider, sessions, ledger, _ = system()
    session = sessions.load("s")
    turn = session.turns[0].model_copy(update={"sim_exchanges": [exchange(1)]})
    sessions.save(session.model_copy(update={"turns": [turn]}))
    audio = ObservedAudio()
    dependencies = VoiceDependencies(ledger, audio, provider, Sessions(sessions))
    service = DurableVoiceService(dependencies)
    op = replace(operation(), exchange_sequence=1 if change == "reaction" else None)
    stream = await service.speech(op)
    assert await anext(stream) == b"\0\1"

    # Act: the learning loop moves the source while the provider is still streaming.
    updated = (
        turn.model_copy(update={"seq": 2, "run_id": "next-turn"})
        if change == "turn"
        else turn.model_copy(update={"sim_exchanges": [exchange(1), exchange(2)]})
    )
    sessions.save(session.model_copy(update={"turns": [updated]}))
    with pytest.raises(VoiceError, match="moved on"):
        _ = [chunk async for chunk in stream]

    # Assert: stale audio cannot be replayed or regenerated by a new service instance.
    assert audio.stored_key is not None
    with pytest.raises(FileNotFoundError):
        await audio.get(audio.stored_key)
    with pytest.raises(VoiceError):
        await DurableVoiceService(dependencies).speech(op)
    assert provider.speeches == 1
    assert provider.ended
    assert sessions.load("s").turns == [updated]
